Add initial CFR and Kuhn Poker implementation
CognitivePlay/dd-cfr pull request #10
Opened 2023-05-27 19:07 UTC by chirnsch

2023-05-27 21:59 UTC, DavidToneian commented on src/dd_cfr/algorithms/cfr.py
> +        for state in sorted(self.cummulative_policies.keys()):
Why does this need to be `sorted`? Is this behavior depended upon somewhere?

2023-05-27 21:59 UTC, DavidToneian commented on src/dd_cfr/algorithms/cfr.py
> +        Recurisvely traverses the game tree.
I don't care much, but I think there's a linter rule that says that docstrings should be in the imperative (i.e., `Recursively traverse [...]` instead of `traverses`). Though evidently the linter didn't find this case. :)

2023-05-27 21:59 UTC, DavidToneian commented on src/dd_cfr/algorithms/cfr.py
> +
Spurious newline

2023-05-27 21:59 UTC, DavidToneian commented on src/dd_cfr/algorithms/cfr.py
> +            if game.get_active_player() == common.CHANCE_PLAYER:
Instead of having `common.CHANCE_PLAYER`, maybe one should have `game.active_player_is_chance_player()`?

2023-05-27 21:59 UTC, DavidToneian commented on src/dd_cfr/algorithms/cfr.py
> +            self._traverse(game(), [1, 1, 1])
`[1, 1, 1]` is hard-coded for Kuhn poker I suppose?

2023-05-27 21:59 UTC, DavidToneian commented on src/dd_cfr/games/base_game.py
> +        return (player + 1) % 2
Assumes a two-player game (and that the chance player is not a player).

Let's maybe have `Game`s declare their number of players, and `assert` here that it's `2`?

2023-05-27 21:59 UTC, DavidToneian commented on src/dd_cfr/games/kuhn_poker.py
> +        if cards is None:
Shorter alternative, though I don't have strong feelings either way:

```
self._cards = cards or []
self._history = history or []
```

2023-05-27 21:59 UTC, DavidToneian commented on src/dd_cfr/algorithms/cfr.py
> +            payoffs = [0.0, 0.0]
Assumes a two-player game (and that the chance player is not a player).

Let's maybe have `Game`s declare their number of players, and `assert` here that it's `2`?

(Same below for `range(2)`, `get_inactive_player`.)

2023-05-27 21:59 UTC, DavidToneian commented on src/dd_cfr/games/kuhn_poker.py
> +            return ""
Would this be an error state? If yes, why not just `assert len(self._cards) >= 2`? If no, why the `pragma: no cover`?

2023-05-27 21:59 UTC, DavidToneian commented on src/dd_cfr/games/kuhn_poker.py
> +        if self._history[-1].action == Action.BET:
Let's make this an `assert`, and save the `raise` with `pragma: no cover` below.

2023-05-27 21:59 UTC, DavidToneian commented on src/dd_cfr/games/kuhn_poker.py
> +            )  # pragma: no cover
This could be covered in a test, or treated with an `assert`.

2023-05-29 10:46 UTC, chirnsch commented on src/dd_cfr/algorithms/cfr.py
> +        for state in sorted(self.cummulative_policies.keys()):
Sorting is not needed, removed. I'm sorting in the printing function to make the order deterministic, but no need to sort here (artifact from previous implementation).

2023-05-29 11:00 UTC, chirnsch commented on src/dd_cfr/algorithms/cfr.py
> +            self._traverse(game(), [1, 1, 1])
Added more documentation and used a tuple instead of a list to make the type annotation clearer. The reach probabilities are for player 1, player 2, and the chance player - which should be appliciaple for all games. At the start of the game, the reach probabilities are `1` for all players.

2023-05-29 11:05 UTC, chirnsch commented on src/dd_cfr/algorithms/cfr.py
> +            if game.get_active_player() == common.CHANCE_PLAYER:
I think the best might actually be to have a Player ENUM for Player 1, Player 2, and the chance player, with some functionality to e.g. get the other non-chance player (which I currently added in base_game.py).

I'd do some refactoring as a follow-up, added a TODO in common.py.

2023-05-29 11:07 UTC, chirnsch commented on src/dd_cfr/algorithms/cfr.py
> +
Thanks, done.

2023-05-29 11:09 UTC, chirnsch commented on src/dd_cfr/games/kuhn_poker.py
> +        if cards is None:
This would also create new empty lists if cards or history is empty, which is not an issue but I don't like conceptually.

I chose a middleground one-layer instead.

2023-05-29 11:13 UTC, chirnsch commented on src/dd_cfr/games/kuhn_poker.py
> +        if self._history[-1].action == Action.BET:
One of the linters (I believe) complained about the usage of assert, since it can be disabled in production. Would you prefer to change the linter behavior and switch to assert?

2023-05-29 11:13 UTC, chirnsch commented on src/dd_cfr/games/kuhn_poker.py
> +            )  # pragma: no cover
(same as above).

2023-05-29 11:16 UTC, chirnsch commented on src/dd_cfr/algorithms/cfr.py
> +            payoffs = [0.0, 0.0]
Let's discuss offline whether to restrict oureselves to two player games only.

2023-05-29 11:21 UTC, chirnsch commented on src/dd_cfr/games/kuhn_poker.py
> +            return ""
No, that would not be an error - updated the logic and added a comment to make it clear.

2023-06-12 16:52 UTC, DavidToneian requested changes

2023-06-12 16:52 UTC, DavidToneian commented on src/dd_cfr/algorithms/cfr.py
> +        self.cummulative_regrets: dict[
`cumulative` with just one `m`

2023-06-12 16:52 UTC, DavidToneian commented on src/dd_cfr/algorithms/cfr.py
> +        # state, action to regret, to compute current policy.
Somewhat hard to parse. Is `# Maps state and action to regret. Used to compute current policy` correct and more understandable? If so, analogous change in line 22 below.

2023-06-12 16:52 UTC, DavidToneian commented on src/dd_cfr/algorithms/cfr.py
> +            False.
Refer to https://arxiv.org/abs/1407.5042 again (and use `regret-matching+` if that's the nomenclature they use)?

2023-06-12 16:52 UTC, DavidToneian commented on src/dd_cfr/algorithms/cfr.py
> +        """
Maybe as a todo for the future, but we could check here whether `reach_probs` is of length `3`.

2023-06-12 16:52 UTC, DavidToneian commented on src/dd_cfr/games/base_game.py
> +        """Return the payoffs for all players in order."""
Somewhat unclear whether "in order" means "for players 0, 1, ..., in that order", or "in the order of play, starting with the active player."

2023-06-12 16:52 UTC, DavidToneian commented on src/dd_cfr/games/kuhn_poker.py
> +        :raises ValueError: If legal actions are retrieved for an  impossible state.
Nit: two spaces before `impossible`

2023-06-12 17:05 UTC, chirnsch commented on src/dd_cfr/algorithms/cfr.py
> +        self.cummulative_regrets: dict[
Thanks, done.

2023-06-12 17:05 UTC, chirnsch commented on src/dd_cfr/algorithms/cfr.py
> +            False.
Done.

2023-06-12 17:05 UTC, chirnsch commented on src/dd_cfr/games/base_game.py
> +        """Return the payoffs for all players in order."""
Done (the former option).

2023-06-12 17:05 UTC, chirnsch commented on src/dd_cfr/games/base_game.py
> +        return (player + 1) % 2
Discussed offline, we focus on 2 player games for now.

2023-06-12 17:05 UTC, chirnsch commented on src/dd_cfr/games/kuhn_poker.py
> +        :raises ValueError: If legal actions are retrieved for an  impossible state.
Thanks, done.

2023-06-12 17:05 UTC, chirnsch commented on src/dd_cfr/algorithms/cfr.py
> +        # state, action to regret, to compute current policy.
Thanks, updated to your suggestion.

2023-06-12 17:05 UTC, chirnsch commented on src/dd_cfr/algorithms/cfr.py
> +        """
I'd leave this as is - there are many things we could asset as well, e.g. that all probabilities are <= 1, but I wouldn't check all of them exhaustively (at least for now).

2023-06-12 17:08 UTC, DavidToneian approved these changes

2023-06-12 17:09 UTC, merged