Add first components of the `Schnapsen` game.
CognitivePlay/dd-cfr pull request #13
Opened 2023-05-27 20:59 UTC by DavidToneian

2023-05-29 21:05 UTC, chirnsch requested changes

2023-05-29 21:05 UTC, chirnsch commented on tests/games/schnapsen/test_suit.py
> +    assert len(list(Suit)) == 4
Simply `len(Suit)` works as well.

2023-05-29 21:05 UTC, chirnsch commented on src/dd_cfr/games/schnapsen/card_value.py
> +    def __lt__(self, rhs: "CardValue") -> bool:
You could consider using `from __future__ import annotations` and dropping the quotes.

2023-05-29 21:05 UTC, chirnsch commented on src/dd_cfr/games/schnapsen/deck.py
> +from .card import Card
As discussed, let's follow the recommendation here: https://google.github.io/styleguide/pyguide.html#22-imports

`Use import statements for packages and modules only, not for individual classes or functions.`

2023-05-29 21:05 UTC, chirnsch commented on src/dd_cfr/games/schnapsen/deck.py
> +        return 5 * 4
len(Suit) * len(CardValue)?

2023-05-29 21:05 UTC, chirnsch commented on src/dd_cfr/games/schnapsen/deck.py
> +    def get_turn_up_card(self) -> Card:
Maybe `get_open_card`? Or is `turn_up` the "official" name?

2023-05-29 21:05 UTC, chirnsch commented on src/dd_cfr/games/schnapsen/deck.py
> +        return [Card(suit, value) for suit in list(Suit) for value in list(CardValue)]
I believe you can drop the `list()` for iterrating.

2023-05-29 21:05 UTC, chirnsch commented on src/dd_cfr/games/schnapsen/hand.py
> +import typing
The Google styleguide recommends importing the specific types from typing directly: https://google.github.io/styleguide/pyguide.html#31912-imports-for-typing.

Should we follow that advice?

2023-05-29 21:05 UTC, chirnsch commented on src/dd_cfr/games/schnapsen/hand.py
> +import typing
Although that can also be annoying, since you need to add/remove individual types every time a new one is added. * import would be the other option, but I'm not sure if we want to do that.

What do you think?

2023-05-30 18:22 UTC, DavidToneian commented on tests/games/schnapsen/test_suit.py
> +    assert len(list(Suit)) == 4
Thanks, implemented

2023-05-30 18:24 UTC, DavidToneian commented on src/dd_cfr/games/schnapsen/card_value.py
> +    def __lt__(self, rhs: "CardValue") -> bool:
Thanks, implemented.

2023-05-30 18:24 UTC, DavidToneian commented on src/dd_cfr/games/schnapsen/deck.py
> +        return 5 * 4
Works for me :) Implemented, thanks.

2023-05-30 18:25 UTC, DavidToneian commented on src/dd_cfr/games/schnapsen/deck.py
> +    def get_turn_up_card(self) -> Card:
It's what Wikipedia uses, at least: https://en.wikipedia.org/wiki/Schnapsen

I'm not familiar with English card-game terminology though, so if "open card" is a well-known alternative, I'm happy to refactor.

2023-05-30 18:27 UTC, DavidToneian commented on src/dd_cfr/games/schnapsen/deck.py
> +        return [Card(suit, value) for suit in list(Suit) for value in list(CardValue)]
Indeed, wasn't aware, had misunderstood the Python documentation. Thanks!

2023-06-02 16:38 UTC, DavidToneian commented on src/dd_cfr/games/schnapsen/deck.py
> +from .card import Card
Done

2023-06-02 16:40 UTC, DavidToneian commented on src/dd_cfr/games/schnapsen/hand.py
> +import typing
Given that we're following other Google recommendations, I'd go with this one as well (and not import `*`).

Another, somewhat related, question is: Should we upgrade to Python 3.9? That would allow us to use e.g. `list` instead of `typing.List` in type hints. I'd be for it.

2023-06-04 20:54 UTC, chirnsch requested changes

2023-06-04 20:54 UTC, chirnsch commented on src/dd_cfr/games/schnapsen/card.py
> +    def __lt__(self, rhs: Value) -> bool:
nit (up to you): I've predominantly seen this called "other" in Python before, e.g. see

https://github.com/search?q=repo%3Apython%2Fcpython+__lt__&type=code

2023-06-04 20:54 UTC, chirnsch commented on src/dd_cfr/games/schnapsen/hand.py
> +import typing
Yes let's upgrade to 3.9,  I'd be for it as well.

2023-06-04 20:54 UTC, chirnsch commented on src/dd_cfr/games/schnapsen/card_collection.py
> +        if index not in range(self.get_number_of_cards()):
Interesting way of doing this! It's linear in the number of cards, but since there are at most 5 I guess this is fine.

More common (and therefore potentially easier to read, even though yours shows the intention more clearly) would be to use `if index < 0 or index >= self.get_number_of_cards()`. Up to you whether you prefer to switch.

2023-06-04 20:54 UTC, chirnsch commented on src/dd_cfr/games/schnapsen/card_collection.py
> +        :raises ValueError: Raises if the hand does not contain exactly 4 cards.
Nit: potentially drop the "Raises" here and elsewhere, or are you adding it because of how the auto generated html documetnation looks? (I read this as `raises ValueError [Raises] if [...]`.

2023-06-04 20:54 UTC, chirnsch commented on src/dd_cfr/games/schnapsen/card_collection.py
> +class WonCards:
[comment only, no need to change anything]

We may want to change the representation at some point to either more a fine-grained (e.g. containing information about each trick), or efficient version (e.g. one that directly gives a vector of won cards), but this is looks like the most useful first version.

2023-06-04 20:54 UTC, chirnsch commented on src/dd_cfr/games/schnapsen/card_collection.py
> +    def __init__(self) -> None:
We'll likely also want a constructor that accepts a set of won cards later to copy a game state, but fine to add that as a follow-up.

Related comment: It might make sense in he future to unify some of the functionality of `WonCards` and `Hand` into something like `CardCollections` as a base class at some point. Also fine to leave, since we do not really know how these classes will change once we optimize more for different algorithms.

2023-06-05 16:10 UTC, DavidToneian commented on src/dd_cfr/games/schnapsen/card.py
> +    def __lt__(self, rhs: Value) -> bool:
Appreciate hints to become more pythonic. :)

2023-06-05 16:11 UTC, DavidToneian commented on src/dd_cfr/games/schnapsen/card_collection.py
> +        if index not in range(self.get_number_of_cards()):
Agree; implemented

2023-06-05 16:46 UTC, chirnsch approved these changes

2023-06-05 16:47 UTC, merged